### ISSUE TITLE
Rework "is_stock" column at tracks file to have in mind Lego tracks

### ISSUE THREAD

**Issue by EstebanMz** [Re-Volt-America/RVA-Data#19]
As the title of the column itself says,  "is_stock" is just a boolean that checks whether a track is stock, else it tags it as a custom track.
The next season will include more than just two lego tracks, and with how the tracklist generator currently works, it can lead to miss more than a lego track every week.
My suggestion includes giving an unique tag (it can be just a number) to every couple of lego tracks, in that way, for example, if Calaboq is picked by the randomizer to be played on Friday for this week, then on Saturday's tracklist it must pick User-Deli: XL because, in this example, they share the same tag in the database.

**Comment by BGMP** [comment]
Relates to https://github.com/Re-Volt-America/RVA/issues/125

**Comment by BGMP** [comment]
Resolved by https://github.com/Re-Volt-America/RVA-Data/commit/638488df2fb198826268f4c60d0063541190c8c5 & https://github.com/Re-Volt-America/RVA/commit/7b04325065a14a33290c19d0d25b09af8e253855
